// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '***YOUR API KEY ****',
    appId: '1:243676341259:web:dd3c1fed250d0743e1930e',
    messagingSenderId: '243676341259',
    projectId: 'tarim-41e24',
    authDomain: 'tarim-41e24.firebaseapp.com',
    storageBucket: 'tarim-41e24.firebasestorage.app',
    measurementId: 'G-HK5X89PKC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKtU0DCyagNDNs2DnbISkoTsDO45lcIck',
    appId: '1:243676341259:android:86acfea7e35fba27e1930e',
    messagingSenderId: '243676341259',
    projectId: 'tarim-41e24',
    storageBucket: 'tarim-41e24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFiOlq-cRnuQLkIcIWoV01I6cHzo29JAk',
    appId: '1:243676341259:ios:5d6280f71885333ae1930e',
    messagingSenderId: '243676341259',
    projectId: 'tarim-41e24',
    storageBucket: 'tarim-41e24.firebasestorage.app',
    iosBundleId: 'com.example.tarim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFiOlq-cRnuQLkIcIWoV01I6cHzo29JAk',
    appId: '1:243676341259:ios:5d6280f71885333ae1930e',
    messagingSenderId: '243676341259',
    projectId: 'tarim-41e24',
    storageBucket: 'tarim-41e24.firebasestorage.app',
    iosBundleId: 'com.example.tarim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy1lOE8zFCgPw3tzsriTjf2Dae0TypdTY',
    appId: '1:243676341259:web:de0c4430d844d2cae1930e',
    messagingSenderId: '243676341259',
    projectId: 'tarim-41e24',
    authDomain: 'tarim-41e24.firebaseapp.com',
    storageBucket: 'tarim-41e24.firebasestorage.app',
    measurementId: 'G-76B5V3TJ3N',
  );
}
